# Generated by Django 2.1.1 on 2019-11-21 09:24

import demo1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='张三', max_length=20, validators=[demo1.models.name_min])),
                ('password', models.CharField(default='123456', max_length=20)),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女')], error_messages={'blank': 'no blank', 'null': 'no null'})),
            ],
        ),
    ]
