# Generated by Django 2.1.1 on 2019-11-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0002_auto_20191120_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女')])),
            ],
        ),
    ]
