# Generated by Django 2.1.1 on 2019-11-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='张三', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], error_messages={'blank': 'no blank', 'null': 'no null'}),
        ),
    ]
